language: rust
cache: cargo
before_script: (cargo install rustfmt || true)
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
script:
- |
  cargo fmt -- --write-mode=diff &&
  cargo build &&
  cargo test
